name: build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: clone nixos-config
        uses: actions/checkout@v4
        with:
          repository: pilz0/nixos-config
          path: nixos-config
          persist-credentials: false

      - name: build with colmena
        run: nix develop . && ./colmena-wrapped.sh build "*"
